#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerSample.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="AsusTek")]
	public partial class AsusDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public AsusDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["AsusTekConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AsusDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AsusDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AsusDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AsusDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.CheckExistedField")]
		public ISingleResult<CheckExistedFieldResult> CheckExistedField([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CustomerID", DbType="Int")] System.Nullable<int> customerID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Value", DbType="NVarChar(MAX)")] string value, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mode", DbType="Int")] System.Nullable<int> mode)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), customerID, value, mode);
			return ((ISingleResult<CheckExistedFieldResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetIdByFullName")]
		public ISingleResult<GetIdByFullNameResult> GetIdByFullName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FullName", DbType="NVarChar(MAX)")] string fullName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fullName);
			return ((ISingleResult<GetIdByFullNameResult>)(result.ReturnValue));
		}
	}
	
	public partial class CheckExistedFieldResult
	{
		
		private int _CheckExist;
		
		public CheckExistedFieldResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckExist", DbType="Int NOT NULL")]
		public int CheckExist
		{
			get
			{
				return this._CheckExist;
			}
			set
			{
				if ((this._CheckExist != value))
				{
					this._CheckExist = value;
				}
			}
		}
	}
	
	public partial class GetIdByFullNameResult
	{
		
		private int _CustomerID;
		
		public GetIdByFullNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int NOT NULL")]
		public int CustomerID
		{
			get
			{
				return this._CustomerID;
			}
			set
			{
				if ((this._CustomerID != value))
				{
					this._CustomerID = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
